# Generated by Django 2.2.3 on 2019-07-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_message', to='wall_app.Message'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='users_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_users', to='wall_app.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='users_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='wall_app.User'),
        ),
    ]
