# Generated by Django 2.2.3 on 2019-07-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20190718_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='users_m',
            new_name='user',
        ),
    ]
